"use client";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { useState } from "react";
import type { loadCompetitionStructure, getGroupStandings } from "@/lib/competition-structure-service";
type Stages = Awaited<ReturnType<typeof loadCompetitionStructure>>;
type Table = Awaited<ReturnType<typeof getGroupStandings>>;
export function CompetitionStructureManager({ competitionId, stages, tables, teams, canWrite }: { competitionId: string; stages: Stages; tables: Table[]; teams: { id: string; name: string }[]; canWrite: boolean }) {
  const router = useRouter(), params = useSearchParams(); const [message, setMessage] = useState(""), [busy, setBusy] = useState(false);
  const stageId = params.get("stageId") ?? stages[0]?.id ?? "", groupId = params.get("groupId") ?? "";
  function selectStructure(key: string, value: string) { const next = new URLSearchParams(params.toString()); next.set("stageId", key === "stageId" ? value : stageId); if (key === "groupId") next.set("groupId", value); else next.delete("groupId"); next.delete("roundId"); next.delete("page"); router.replace(`/admin/competitions/${competitionId}?${next}`); }
  const setStageId = (id: string) => selectStructure("stageId", id);
  const setGroupId = (id: string) => selectStructure("groupId", id);
  const stage = stages.find((s) => s.id === stageId), group = stage?.groups.find((g) => g.id === groupId);
  async function save(body: unknown) {
    if (busy) return; setBusy(true); setMessage("");
    try { const response = await fetch(`/api/admin/competitions/${competitionId}/structure`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "保存失败。"); setMessage("已保存。相关排名和出线确认如依据改变将标记待复核。"); router.refresh(); }
    catch (error) { setMessage(error instanceof Error ? error.message : "保存失败。"); } finally { setBusy(false); }
  }
  function create(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const action = String(form.get("action")); void save({ action, name: form.get("name"), type: form.get("type"), stageId, groupId, sortOrder: Number(form.get("sortOrder") ?? 0) }); }
  return <section className="admin-panel"><header className="admin-panel-header"><div><h2>赛程结构与小组积分</h2><p>人工记录已确定的阶段、分组和轮次；旧比赛保留未结构化状态。出线确认不会创建对阵。</p></div></header><div className="admin-panel-body"><p aria-live="polite">{message}</p>{canWrite ? <form className="admin-form" onSubmit={create}><div className="admin-form-grid"><label><span>新增阶段</span><input name="name" required maxLength={80} placeholder="小组赛 / 淘汰赛" /></label><label><span>阶段类型</span><select name="type"><option value="GROUP">小组赛</option><option value="KNOCKOUT">淘汰赛</option><option value="OTHER">其他（可不分组）</option></select></label><label><span>显示顺序</span><input name="sortOrder" type="number" min={0} max={9999} defaultValue={stages.length} /></label></div><button className="admin-button" disabled={busy} name="action" value="stage" onClick={(e) => { e.currentTarget.form?.querySelector<HTMLInputElement>('[name="action"]')?.setAttribute("value", "stage"); }} type="submit">建立阶段</button><input name="action" type="hidden" value="stage" /></form> : null}
    <div className="admin-filter-bar"><label><span>当前阶段</span><select value={stageId} onChange={(e) => { setStageId(e.target.value); }}><option value="">选择阶段</option>{stages.map((s) => <option key={s.id} value={s.id}>{s.name}</option>)}</select></label>{stage?.groups.length ? <label><span>当前小组</span><select value={groupId} onChange={(e) => setGroupId(e.target.value)}><option value="">全部 / 无分组</option>{stage.groups.map((g) => <option key={g.id} value={g.id}>{g.name}</option>)}</select></label> : null}{canWrite ? <><Link className="admin-button admin-button-secondary" href={`/admin/matches/new?competitionId=${competitionId}&stageId=${stageId}&groupId=${groupId}`}>新建本阶段比赛</Link><Link href={`/admin/competitions/import?competitionId=${competitionId}&kind=matches`}>批量导入赛程</Link></> : null}</div>
    {canWrite && stage ? <><form className="admin-form" onSubmit={create}><div className="admin-form-grid"><label><span>新增{stage.type === "GROUP" && !groupId ? "小组或轮次" : "轮次"}</span><input name="name" required maxLength={80} placeholder={stage.type === "GROUP" && !groupId ? "A组 / 第1轮" : "第1轮 / 半决赛"} /></label><label><span>结构</span><select name="action">{stage.type === "GROUP" ? <option value="group">小组</option> : null}<option value="round">轮次</option></select></label><label><span>显示顺序</span><input name="sortOrder" type="number" min={0} max={9999} defaultValue={0} /></label></div><button disabled={busy} className="admin-button" type="submit">建立</button></form><div className="admin-inline-checks"><button className="admin-button admin-button-secondary" disabled={busy} onClick={() => { if (window.confirm("仅未被引用的结构可删除。确认删除当前阶段？")) void save({ action: "delete", entity: "stage", id: stage.id }); }} type="button">删除空阶段</button>{group ? <button className="admin-button admin-button-secondary" disabled={busy} onClick={() => { if (window.confirm("确认删除当前小组？历史引用会阻止删除。")) void save({ action: "delete", entity: "group", id: group.id }); }} type="button">删除空小组</button> : null}</div></> : null}
    {stage ? <div className="admin-inline-checks">{stage.rounds.filter((r) => !groupId || !r.groupId || r.groupId === groupId).map((r) => <span key={r.id}>{canWrite ? <Link href={`/admin/matches/new?competitionId=${competitionId}&stageId=${stage.id}&groupId=${r.groupId ?? groupId}&roundId=${r.id}`}>{r.groupId && !groupId ? `${stage.groups.find((g) => g.id === r.groupId)?.name ?? ""} · ` : ""}{r.name} · 新建比赛</Link> : <span>{r.name}</span>}{canWrite ? <button disabled={busy} onClick={() => { if (window.confirm("确认删除未被比赛引用的轮次？")) void save({ action: "delete", entity: "round", id: r.id }); }} type="button" aria-label={`删除${r.name}`}>×</button> : null}</span>)}</div> : null}
    {canWrite && group && stage ? <form key={group.id + group.members.map((m) => m.teamId).join()} className="admin-form" onSubmit={(e) => { e.preventDefault(); const f = new FormData(e.currentTarget); void save({ action: "members", groupId: group.id, teamIds: f.getAll("teamIds"), reason: "人工核对抽签结果" }); }}><h3>{group.name} · 手动分配参赛球队</h3><p>未分组球队可直接选择；本阶段已在其他组的球队不能重复分配。移出已有比赛球队会被阻止。</p><div className="admin-checkbox-list">{teams.map((t) => { const assigned = stage.groups.find((g) => g.members.some((m) => m.teamId === t.id)); return <label key={t.id}><input name="teamIds" value={t.id} type="checkbox" disabled={Boolean(assigned && assigned.id !== group.id)} defaultChecked={assigned?.id === group.id} /><span>{t.name}{assigned ? ` · ${assigned.name}` : " · 未分组"}</span></label>; })}</div><button className="admin-button" disabled={busy} type="submit">保存组成员</button></form> : null}
    {tables.filter((t) => t.group.stageName === stage?.name && (!groupId || t.group.id === groupId)).map((t) => <GroupTable key={t.group.id + t.fingerprint + t.qualificationFingerprint} table={t} canWrite={canWrite} busy={busy} save={save} />)}
    {!stages.length ? <p>暂无正式结构，可先建立“小组赛”并人工添加 A/B/C/D。</p> : null}</div></section>;
}
function GroupTable({ table: t, canWrite, busy, save }: { table: Table; canWrite: boolean; busy: boolean; save: (body: unknown) => Promise<void> }) {
  const [order, setOrder] = useState(t.rows.map((r) => r.id));
  function move(i: number, d: number) { const next = [...order]; [next[i], next[i + d]] = [next[i + d], next[i]]; setOrder(next); }
  return <section className="admin-form-section"><h3>{t.group.name} · 积分与人工确认</h3><p>{!t.hasResults ? "尚未开赛" : t.rankingStale ? "旧排名依据已变化，待复核" : t.tied && !t.rankingConfirmed ? "同分，最终次序待确认" : t.rankingConfirmed ? "人工次序已确认" : "按积分、净胜球、进球数临时排序"}{t.qualificationStale ? " · 出线确认待复核；已建淘汰赛对阵保持原样，请人工检查。" : ""}</p><ul>{t.affectedMatches.map((m) => <li key={m.id}><Link href={`/admin/matches/${m.id}`}>待核查：{m.homeTeam.name} vs {m.awayTeam.name}（{m.status === "COMPLETED" ? "已有赛果" : m.status === "CANCELLED" ? "已取消" : "已安排"}）</Link></li>)}</ul><div className="admin-table-scroll"><table className="admin-data-table"><thead><tr><th>球队</th>{["场次", "胜", "平", "负", "进球", "失球", "净胜球", "积分"].map((h) => <th key={h}>{h}</th>)}{canWrite ? <th>人工次序</th> : null}</tr></thead><tbody>{order.map((id, i) => { const r = t.rows.find((r) => r.id === id)!; return <tr key={id}><td>{r.name}{t.qualifiedTeamIds.includes(id) ? " · 已确认出线" : ""}</td>{[r.played, r.won, r.drawn, r.lost, r.goalsFor, r.goalsAgainst, r.goalDifference, r.points].map((n, j) => <td key={j}>{n}</td>)}{canWrite ? <td><button disabled={i === 0 || busy} onClick={() => move(i, -1)} type="button" aria-label={`上移${r.name}`}>↑</button><button disabled={i === order.length - 1 || busy} onClick={() => move(i, 1)} type="button" aria-label={`下移${r.name}`}>↓</button></td> : null}</tr>; })}</tbody></table></div>{canWrite ? <form className="admin-form" onSubmit={(e) => { e.preventDefault(); const f = new FormData(e.currentTarget); const action = (e.nativeEvent as SubmitEvent).submitter as HTMLButtonElement; const kind = action.value; void save({ action: "confirm", groupId: t.group.id, fingerprint: kind === "QUALIFICATION" ? t.qualificationFingerprint : t.fingerprint, kind, teamIds: kind === "RANKING" ? order : kind === "AUTO" ? [] : f.getAll("qualified"), reason: String(f.get("reason") ?? "") }); }}><label><span>适用规程 / 原因</span><textarea name="reason" required maxLength={500} placeholder="提前确认需以 提前确认： 开头并说明依据" /></label><div className="admin-checkbox-list">{order.map((id) => <label key={id}><input name="qualified" type="checkbox" value={id} defaultChecked={t.qualifiedTeamIds.includes(id)} />{t.rows.find((r) => r.id === id)?.name}</label>)}</div><div className="admin-inline-checks"><button disabled={busy || !t.hasResults} className="admin-button" type="submit" value="RANKING">确认同分次序</button><button disabled={busy} className="admin-button admin-button-secondary" type="submit" value="AUTO">恢复自动显示顺序</button><button disabled={busy} className="admin-button" type="submit" value="QUALIFICATION">确认勾选球队出线（按当前顺序）</button></div></form> : null}</section>;
}
