"use client";
import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import { MediaVisibilityButton } from "@/components/admin/media-visibility-button";
import { formatRefereeDateTime } from "@/lib/referee-presenters";

type Usage = { id: string; title: string; status: string; type: string; ways: string[] };
type Asset = { id: string; originalFilename: string; mimeType: string; size: number; visibility: string; altText: string | null; createdAt: string; fileStatus: string; usage: Usage[]; usageCount: number; uploadedByAdmin: { displayName: string } | null };
const wayNames = ["封面", "附件", "正式文件", "正文图片"];
function bytes(size: number) { return size >= 1048576 ? `${(size / 1048576).toFixed(1)} MB` : `${Math.max(1, Math.round(size / 1024))} KB`; }
export function MediaLibraryTable({ items, canWrite }: { items: Asset[]; canWrite: boolean }) {
  const [active, setActive] = useState<Asset | null>(null);
  return <><div className="admin-table-scroll"><table className="admin-data-table ops-media-table"><thead><tr><th>文件</th><th>状态</th><th>使用情况</th><th>上传信息</th><th>操作</th></tr></thead><tbody>{items.map((asset) => <tr key={asset.id}><td><div className="ops-media-file">{asset.mimeType.startsWith("image/") && asset.fileStatus === "AVAILABLE" ? <Image src={`/media/${asset.id}`} alt="" width={56} height={48} unoptimized /> : <span aria-hidden="true" className="ops-file-icon">PDF</span>}<div><strong title={asset.originalFilename}>{asset.originalFilename}</strong><small>{asset.mimeType === "application/pdf" ? "PDF" : asset.mimeType.replace("image/", "").toUpperCase()} · {bytes(asset.size)}</small>{asset.altText ? <small className="ops-media-alt">{asset.altText}</small> : null}</div></div></td><td><span className="admin-media-visibility" data-visibility={asset.visibility}>{asset.visibility === "PUBLIC" ? "公开文件" : "仅后台"}</span>{asset.fileStatus === "MISSING" ? <small className="admin-file-missing">文件缺失</small> : null}</td><td><strong>{asset.usageCount ? `用于 ${asset.usageCount} 篇内容` : "未使用"}</strong>{asset.usageCount ? <><small>{wayNames.filter((w) => asset.usage.some((u) => u.ways.includes(w))).map((w) => `${w} ${asset.usage.filter((u) => u.ways.includes(w)).length}`).join(" · ")}</small><button type="button" onClick={() => setActive(asset)}>查看详情 →</button></> : null}</td><td><strong>{asset.uploadedByAdmin?.displayName ?? "兼容管理员"}</strong><small>{formatRefereeDateTime(new Date(asset.createdAt))}</small></td><td><div className="admin-table-actions">{asset.fileStatus === "AVAILABLE" ? <a href={`/media/${asset.id}`} rel="noreferrer" target="_blank">打开</a> : <span>不可用</span>}{canWrite ? <details className="ops-media-actions"><summary>更多</summary><MediaVisibilityButton id={asset.id} visibility={asset.visibility} /></details> : null}</div></td></tr>)}</tbody></table></div>{active ? <div aria-modal="true" className="admin-modal-backdrop" role="dialog" aria-label={`${active.originalFilename}使用详情`}><div className="admin-modal"><header><div><span>MEDIA USAGE</span><h2>{active.originalFilename}</h2></div><button aria-label="关闭" onClick={() => setActive(null)} type="button">×</button></header><div className="ops-media-detail"><strong>使用情况 · {active.usageCount}</strong><div className="ops-media-way-counts">{wayNames.map((way) => <span key={way}>{way} · {active.usage.filter((u) => u.ways.includes(way)).length}</span>)}</div><div className="ops-detail-scroll">{active.usage.map((u) => <div key={u.id}><strong>{u.title}</strong><small>{u.ways.join(" · ")} · {u.status}</small><Link href={`/admin/content/news/${u.id}`}>查看内容</Link></div>)}</div></div></div></div> : null}</>;
}
