"use client";
import { useState } from "react";
export type PickedMedia = { id: string; originalFilename: string; mimeType: string; visibility: "PUBLIC" | "PRIVATE"; fileStatus?: string };
export function MediaPicker({ mode, onSelect, onBusy }: { mode: "images" | "files" | "all"; onSelect: (asset: PickedMedia) => void; onBusy?: (busy: boolean) => void }) {
  const [open, setOpen] = useState(false), [query, setQuery] = useState(""), [page, setPage] = useState(1), [pages, setPages] = useState(1), [items, setItems] = useState<PickedMedia[]>([]), [visibility, setVisibility] = useState("PRIVATE"), [busy, setBusy] = useState(false), [message, setMessage] = useState("");
  async function search(next = 1) {
    setBusy(true); setMessage("");
    try { const response = await fetch(`/api/admin/media?category=${mode === "all" ? "" : mode}&query=${encodeURIComponent(query)}&page=${next}`); const result = await response.json(); if (!response.ok) throw new Error(result.error || "读取失败。"); setItems(result.items); setPage(result.page); setPages(result.totalPages); setOpen(true); } catch (e) { setMessage(e instanceof Error ? e.message : "读取失败。"); } finally { setBusy(false); }
  }
  async function upload(file: File) {
    if (busy) return; setBusy(true); onBusy?.(true); setMessage("");
    try { const response = await fetch("/api/admin/media", { method: "POST", headers: { "content-type": file.type, "x-nuaafa-filename": encodeURIComponent(file.name), "x-nuaafa-visibility": visibility }, body: file }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "上传失败。"); onSelect(result.asset); setMessage("上传成功，保存内容后建立关联。"); } catch (e) { setMessage(e instanceof Error ? e.message : "上传失败。"); } finally { setBusy(false); onBusy?.(false); }
  }
  return <div className="admin-media-picker"><div className="admin-filter-bar"><label><span>上传{mode === "images" ? "图片" : "附件"}</span><input accept={mode === "images" ? "image/jpeg,image/png,image/webp" : mode === "files" ? "application/pdf" : "image/jpeg,image/png,image/webp,application/pdf"} type="file" disabled={busy} onChange={(e) => { const file = e.target.files?.[0]; if (file) void upload(file); e.target.value = ""; }} /></label><label><span>上传文件访问范围</span><select value={visibility} onChange={(e) => setVisibility(e.target.value)}><option value="PRIVATE">仅后台</option><option value="PUBLIC">公开文件（已确认可公开）</option></select></label><button className="admin-button admin-button-secondary" disabled={busy} onClick={() => { if (open) setOpen(false); else void search(1); }} type="button">{open ? "收起媒体库" : "从媒体库选择"}</button></div><small>公开文件可通过媒体地址访问，放在草稿中不会变为私密。取消文章只移除关联，不删除文件。</small>{open ? <div><div className="admin-filter-bar"><label><span>文件名或说明</span><input value={query} onChange={(e) => setQuery(e.target.value)} /></label><button className="admin-button admin-button-secondary" disabled={busy} type="button" onClick={() => void search(1)}>搜索</button></div><ul>{items.map((a) => <li key={a.id}><span>{a.originalFilename} · {a.visibility === "PUBLIC" ? "公开" : "仅后台"}{a.fileStatus === "MISSING" ? " · 文件缺失" : ""}</span><button className="admin-button admin-button-secondary" type="button" disabled={busy || a.fileStatus === "MISSING"} onClick={() => onSelect(a)}>选择</button></li>)}</ul><div className="admin-pagination"><button disabled={busy || page <= 1} onClick={() => void search(page - 1)} type="button">上一页</button><span>{page} / {pages}</span><button disabled={busy || page >= pages} onClick={() => void search(page + 1)} type="button">下一页</button></div>{!items.length ? <p>没有符合条件的文件。</p> : null}</div> : null}<p aria-live="polite">{message}</p></div>;
}
