"use client";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { useId, useMemo, useState } from "react";
import { WorkspaceDialog } from "@/components/admin/workspace-dialog";
import type { inspectTeamRemoval } from "@/lib/competition-team-removal";
export type GroupingStage = { id: string; name: string; type: string; groups: { id: string; name: string; sortOrder: number; members: { teamId: string }[] }[] };
type Inspection = Awaited<ReturnType<typeof inspectTeamRemoval>>;
export function TeamGroupingManager({ competitionId, stages, teams, canWrite, onSaved }: { competitionId: string; stages: GroupingStage[]; teams: { id: string; name: string }[]; canWrite: boolean; onSaved?: () => void | Promise<void> }) {
  const router = useRouter(), params = useSearchParams();
  const groupFormId = useId();
  const [localStage, setLocalStage] = useState(stages.find((s) => s.type === "GROUP")?.id ?? "");
  const stageId = params.get("stageId") ?? localStage;
  const [search, setSearch] = useState(""), [groupSearch, setGroupSearch] = useState(""), [filter, setFilter] = useState("all"), [target, setTarget] = useState("");
  const [selected, setSelected] = useState<string[]>([]), [page, setPage] = useState(1), [groupPage, setGroupPage] = useState(1);
  const [assignment, setAssignment] = useState<{ ids: string[]; destination: string } | null>(null);
  const [message, setMessage] = useState(""), [busy, setBusy] = useState(false), [groupEditor, setGroupEditor] = useState<{ id?: string; name: string; sortOrder: number } | null>(null);
  const [removal, setRemoval] = useState<Inspection | null>(null), [safeOnly, setSafeOnly] = useState(false), [reason, setReason] = useState("误添加");
  const stage = stages.find((s) => s.id === stageId);
  const memberships = useMemo(() => new Map(stage?.groups.flatMap((g) => g.members.map((m) => [m.teamId, g] as const)) ?? []), [stage]);
  const filtered = teams.filter((t) => t.name.toLowerCase().includes(search.trim().toLowerCase()) && (filter === "all" || filter === "unassigned" && !memberships.has(t.id) || memberships.get(t.id)?.id === filter));
  const groups = stage?.groups.filter((g) => g.name.includes(groupSearch.trim())) ?? [];
  const teamPage = Math.min(page, Math.max(1, Math.ceil(filtered.length / 30))), currentGroupPage = Math.min(groupPage, Math.max(1, Math.ceil(groups.length / 16)));
  const visible = filtered.slice((teamPage - 1) * 30, teamPage * 30);
  async function refresh() { setSelected([]); if (onSaved) await onSaved(); else router.refresh(); }
  async function save(body: unknown) {
    if (busy) return; setBusy(true); setMessage("");
    try { const response = await fetch(`/api/admin/competitions/${competitionId}/structure`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "保存失败"); setGroupEditor(null); setAssignment(null); setMessage("球队分组已保存。"); await refresh(); }
    catch (error) { setMessage(error instanceof Error ? error.message : "保存失败"); } finally { setBusy(false); }
  }
  function assign(ids = selected, destination = target) {
    if (ids.some((id) => memberships.has(id) && memberships.get(id)?.id !== destination)) { setAssignment({ ids, destination }); return; }
    void save({ action: "assign", stageId, groupId: destination || null, teamIds: ids, reason: destination ? "管理员按抽签结果分组" : "移出本小组" });
  }
  async function remove(ids: string[], action: "inspect" | "remove") {
    if (busy) return; setBusy(true); setMessage("");
    try {
      const response = await fetch(`/api/admin/competitions/${competitionId}/teams/remove`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action, teamIds: ids, reason }) }); const data = await response.json();
      if (!response.ok) throw new Error(data.error || "移除失败；名单保持原样。");
      if (action === "inspect") { setRemoval(data); setSafeOnly(false); }
      else { setRemoval(null); setMessage(`已从本赛事移除 ${data.result.removedCount} 支球队。`); await refresh(); }
    } catch (error) { setMessage(error instanceof Error ? error.message : "移除失败"); } finally { setBusy(false); }
  }
  function choose(value: string) { setFilter(value); setPage(1); setSelected([]); setTarget(value !== "all" && value !== "unassigned" ? value : ""); }
  const blocked = removal?.teams.filter((t) => !t.removable) ?? [], finalTeams = removal?.teams.filter((t) => !safeOnly || t.removable) ?? [];
  return <section className="ops-grouping" aria-label="球队与分组"><p role="status">{message}</p>
    <div className="admin-filter-bar"><label><span>小组赛阶段</span><select value={stageId} onChange={(e) => { setLocalStage(e.target.value); const next = new URLSearchParams(params.toString()); next.set("stageId", e.target.value); next.delete("groupId"); router.replace(`?${next}`); choose("all"); setGroupPage(1); }}><option value="">选择阶段</option>{stages.filter((s) => s.type === "GROUP").map((s) => <option key={s.id} value={s.id}>{s.name}</option>)}</select></label><strong>{teams.length} 支球队 · {memberships.size} 支已分组 · {teams.length - memberships.size} 支未分组 · {stage?.groups.length ?? 0} 个小组</strong>{canWrite ? <button type="button" className="admin-button admin-button-secondary" disabled={!stage} onClick={() => setGroupEditor({ name: "", sortOrder: Math.max(-1, ...stage!.groups.map((g) => g.sortOrder)) + 1 })}>新建小组</button> : null}</div>
    <div className="ops-team-layout"><aside className="ops-group-directory" aria-label="小组目录"><label><span>搜索小组</span><input value={groupSearch} onChange={(e) => { setGroupSearch(e.target.value); setGroupPage(1); }} /></label><button type="button" aria-pressed={filter === "all"} onClick={() => choose("all")}>全部球队 · {teams.length}</button><button type="button" aria-pressed={filter === "unassigned"} onClick={() => choose("unassigned")}>未分组 · {teams.length - memberships.size}</button>{groups.slice((currentGroupPage - 1) * 16, currentGroupPage * 16).map((g) => <div key={g.id}><button type="button" aria-pressed={filter === g.id} onClick={() => choose(g.id)}>{g.name} · {g.members.length}队</button>{canWrite ? <button type="button" aria-label={`修改${g.name}`} onClick={() => setGroupEditor(g)}>设置</button> : null}</div>)}{groups.length > 16 ? <nav className="admin-pagination"><button disabled={currentGroupPage <= 1} onClick={() => setGroupPage(currentGroupPage - 1)}>上一页</button><span>{currentGroupPage}/{Math.ceil(groups.length / 16)}</span><button disabled={currentGroupPage * 16 >= groups.length} onClick={() => setGroupPage(currentGroupPage + 1)}>下一页</button></nav> : null}</aside>
    <div><div className="admin-filter-bar"><label><span>搜索球队</span><input value={search} onChange={(e) => { setSearch(e.target.value); setPage(1); setSelected([]); }} /></label><label><span>当前分组</span><select value={filter} onChange={(e) => choose(e.target.value)}><option value="all">全部球队</option><option value="unassigned">只看未分组</option>{stage?.groups.map((g) => <option key={g.id} value={g.id}>{g.name}</option>)}</select></label></div>
    {canWrite ? <p><button type="button" disabled={busy} onClick={() => setSelected(visible.map((t) => t.id))}>全选本页（仅 {visible.length} 支）</button> <button type="button" onClick={() => setSelected([])}>清空选择</button></p> : null}
    <div className="ops-team-list">{visible.map((t) => <div className="ops-team-row" key={t.id}><label>{canWrite ? <input type="checkbox" checked={selected.includes(t.id)} disabled={busy} onChange={(e) => setSelected(e.target.checked ? [...selected, t.id] : selected.filter((id) => id !== t.id))} /> : null}<span><strong>{t.name}</strong><small>{memberships.get(t.id)?.name ?? "未分组球队"}</small></span></label>{canWrite ? <details><summary>更多</summary>{memberships.has(t.id) ? <button type="button" disabled={busy} onClick={() => assign([t.id], "")}>移出本小组</button> : null}<button type="button" className="admin-button-danger" disabled={busy} onClick={() => void remove([t.id], "inspect")}>从本赛事移除</button></details> : null}</div>)}</div>{!filtered.length ? <p>当前没有符合条件的球队。</p> : null}
    {filtered.length > 30 ? <nav className="admin-pagination" aria-label="球队分页"><button type="button" disabled={teamPage <= 1} onClick={() => { setPage(teamPage - 1); setSelected([]); }}>上一页</button><span>{teamPage}/{Math.ceil(filtered.length / 30)}</span><button type="button" disabled={teamPage * 30 >= filtered.length} onClick={() => { setPage(teamPage + 1); setSelected([]); }}>下一页</button></nav> : null}
    {canWrite && selected.length ? <div className="admin-filter-bar ops-selection-bar"><strong>已选 {selected.length} 支球队（本页）</strong>{stage ? <><label><span>分配到</span><select value={target} onChange={(e) => setTarget(e.target.value)}><option value="">移出本小组</option>{stage.groups.map((g) => <option key={g.id} value={g.id}>{g.name}</option>)}</select></label><button type="button" className="admin-button" disabled={busy} onClick={() => assign()}>确认分配</button></> : null}<button type="button" className="admin-button admin-button-danger" disabled={busy} onClick={() => void remove(selected, "inspect")}>移除所选球队</button></div> : null}</div></div>
    {!stage ? <p>暂无小组赛阶段；使用“阶段与轮次”建立后再分组。球队仍可查看与安全移除。</p> : null}
    {assignment ? <WorkspaceDialog title="确认更换分组" busy={busy} onClose={() => setAssignment(null)} footer={<button className="admin-button" disabled={busy} onClick={() => void save({ action: "assign", stageId, groupId: assignment.destination || null, teamIds: assignment.ids, reason: assignment.destination ? "管理员按抽签结果分组" : "移出本小组" })}>确认更改</button>}><p>将 {assignment.ids.length} 支球队{assignment.destination ? `分配到${stage?.groups.find((g) => g.id === assignment.destination)?.name ?? "所选小组"}` : "移出本小组"}。球队仍属于当前赛事。</p><p>服务器将重新检查比赛、排名和出线依赖；危险换组会被阻止。</p><p role="alert">{message}</p></WorkspaceDialog> : null}
    {groupEditor ? <WorkspaceDialog title={groupEditor.id ? "修改小组" : "新建小组"} busy={busy} onClose={() => setGroupEditor(null)} footer={<button className="admin-button" form={groupFormId} type="submit" disabled={busy}>保存小组</button>}><form id={groupFormId} className="admin-form" onSubmit={(e) => { e.preventDefault(); const f = new FormData(e.currentTarget); void save({ action: groupEditor.id ? "updateGroup" : "group", stageId, groupId: groupEditor.id, name: f.get("name"), sortOrder: Number(f.get("sortOrder")) }); }}><label>小组名称<input name="name" required maxLength={80} defaultValue={groupEditor.name} autoFocus /></label><details><summary>更多设置：显示顺序</summary><input name="sortOrder" type="number" min={0} max={9999} defaultValue={groupEditor.sortOrder} /></details></form></WorkspaceDialog> : null}
    {removal ? <WorkspaceDialog title="从本赛事移除" busy={busy} onClose={() => setRemoval(null)} footer={<button type="button" className="admin-button admin-button-danger" disabled={busy || !finalTeams.length || finalTeams.some((t) => !t.removable)} onClick={() => void remove(finalTeams.map((t) => t.id), "remove")}>确认移除 {finalTeams.length} 支球队</button>}><p>赛事：{removal.competitionName}。可移除 {removal.teams.length - blocked.length} 支 · 不可移除 {blocked.length} 支。</p><ul>{removal.teams.map((t) => <li key={t.id}><strong>{t.name}</strong> · {t.removable ? "可移除" : "暂时无法从本赛事移除"}<p>{t.reason} · {t.groups.join("、") || "未分组"}{t.directoryIsPublic ? " · 公开组队目录条目将下线" : ""}</p>{t.matches.map((m) => <Link key={m.id} href={`/admin/matches/${m.id}`}>{m.label} </Link>)}</li>)}</ul><p>仅退出当前赛事及相关小组；组织和其他赛事保持原样。此操作无法一键恢复，不会连带删除比赛或历史。</p>{blocked.length ? <label><input type="checkbox" checked={safeOnly} onChange={(e) => setSafeOnly(e.target.checked)} />仅处理可安全移除的球队，重新确认以下名单</label> : null}<p>最终移除 {finalTeams.length} 支：{finalTeams.map((t) => t.name).join("、")}</p><label>原因<select value={reason} onChange={(e) => setReason(e.target.value)}><option>误添加</option><option>重复创建</option><option>其他</option></select></label><p role="alert">{message}</p></WorkspaceDialog> : null}
  </section>;
}
