import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { mkdtemp, mkdir, readdir, cp, writeFile, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { createClient } from "@libsql/client";
import { activeAdminHref } from "../src/lib/admin-navigation";
import { calculateStandings } from "../src/lib/competition-standings";
import type { ContentPostInput } from "../src/lib/admin-content-input";
async function cli(args: string[], cwd = process.cwd()) {
  const child = spawn(process.execPath, [path.resolve("node_modules/prisma/build/index.js"), ...args], { cwd, env: { ...process.env, RUST_LOG: "trace" }, stdio: ["ignore", "pipe", "pipe"] });
  let output = ""; child.stdout.on("data", (c) => output += c); child.stderr.on("data", (c) => output += c);
  const code = await new Promise<number>((resolve, reject) => { child.once("exit", (c) => resolve(c ?? 1)); child.once("error", reject); });
  assert.equal(code, 0, output); return output;
}
async function main() {
  const root = await mkdtemp(path.join(os.tmpdir(), "nuaafa-ops-r3-1-"));
  process.env.DATABASE_URL = `file:${path.join(root, "ops.db")}`;
  process.env.NUAAFA_UPLOAD_DIR = path.join(root, "uploads");
  process.env.NUAAFA_ISOLATED_SECURITY_TEST = "1";
  process.env.REFEREE_ADMIN_SESSION_SECRET = "ops-isolated-admin-session-secret";
  const evidence: Record<string, unknown> = { root, timezone: process.env.TZ, startedAt: new Date().toISOString() };
  let disconnect: (() => Promise<void>) | undefined;
  try {
    // Fixed HEAD schema and full baseline migrations, then additive deploy upgrade.
    const baseline = path.join(root, "baseline");
    await mkdir(path.join(baseline, "prisma/migrations"), { recursive: true });
    await cp("scripts/fixtures/ops-r3-1-baseline-schema.prisma", path.join(baseline, "prisma/schema.prisma"));
    for (const entry of await readdir("prisma/migrations", { withFileTypes: true })) if (entry.name === "migration_lock.toml" || entry.isDirectory() && entry.name < "20260928090000_ops_r3_1") await cp(path.resolve("prisma/migrations", entry.name), path.join(baseline, "prisma/migrations", entry.name), { recursive: true });
    await writeFile(path.join(baseline, "prisma.config.ts"), `export default ${JSON.stringify({ schema: "prisma/schema.prisma", migrations: { path: "prisma/migrations" }, datasource: { url: process.env.DATABASE_URL } })};`);
    await cli(["migrate", "deploy"], baseline);
    const sql = createClient({ url: process.env.DATABASE_URL });
    await sql.executeMultiple(`
      INSERT INTO Competition(id,slug,name,campus,format,status,createdAt,updatedAt) VALUES('legacy','legacy','合成旧赛事','隔离','FUTSAL','ONGOING',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
      INSERT INTO Team(id,competitionId,name) VALUES('legacy-home','legacy','合成主队'),('legacy-away','legacy','合成客队');
      INSERT INTO Match(id,slug,competitionId,stage,round,kickoff,venue,homeTeamId,awayTeamId,status,createdAt,updatedAt) VALUES('legacy-match','legacy-match','legacy','原阶段文字','原轮次文字','2030-01-01T00:00:00Z','隔离','legacy-home','legacy-away','SCHEDULED',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
      INSERT INTO Referee(id,publicCode,name,createdAt,updatedAt) VALUES('legacy-referee','OPS-OLD','合成裁判',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
      INSERT INTO MediaAsset(id,storageKey,originalFilename,storedFilename,mimeType,size,updatedAt) VALUES('legacy-media','2030/01/00000000-0000.pdf','合成旧文件.pdf','00000000-0000.pdf','application/pdf',9,CURRENT_TIMESTAMP);
      INSERT INTO ContentPost(id,slug,title,summary,content,type,status,updatedAt) VALUES('legacy-post','legacy-post','合成旧处罚','合成', '{"schemaVersion":1,"document":{"type":"doc","content":[]}}','DISCIPLINE','DRAFT',CURRENT_TIMESTAMP);
      INSERT INTO DisciplineDetail(contentPostId,officialMediaId) VALUES('legacy-post','legacy-media');
      INSERT INTO RefereeAppointment(id,matchId,status,revision,updatedAt) VALUES('legacy-appointment','legacy-match','DRAFT',1,CURRENT_TIMESTAMP);
      INSERT INTO AppointmentPosition(id,appointmentId,refereeId,key,label,sortOrder) VALUES('legacy-position','legacy-appointment','legacy-referee','REFEREE','裁判员',0);
      INSERT INTO AppointmentVersion(id,appointmentId,revision,status,snapshot) VALUES('legacy-version','legacy-appointment',1,'DRAFT','{}');
      INSERT INTO AuditLog(id,actorType,action,entityType,entityId,summary) VALUES('legacy-audit','SYSTEM','FIXTURE','Match','legacy-match','合成历史审计');
    `);
    const tables = ["Competition", "Team", "Match", "MediaAsset", "ContentPost", "DisciplineDetail", "Referee", "RefereeAppointment", "AppointmentVersion", "AppointmentPosition", "AuditLog"];
    const counts = async () => Object.fromEntries(await Promise.all(tables.map(async (t) => [t, Number((await sql.execute(`SELECT COUNT(*) AS n FROM "${t}"`)).rows[0].n)])));
    const before = await counts(); await cli(["migrate", "deploy"]); assert.deepEqual(await counts(), before); assert.match(await cli(["migrate", "deploy"]), /No pending migrations/);
    assert.equal((await sql.execute("PRAGMA foreign_key_check")).rows.length, 0); assert.equal((await sql.execute("PRAGMA integrity_check")).rows[0].integrity_check, "ok");
    assert.equal((await sql.execute({ sql: 'SELECT stage FROM Match WHERE id=?', args: ['legacy-match'] })).rows[0].stage, "原阶段文字");
    evidence["MIG-01"] = { before, after: await counts(), foreignKeys: 0, integrity: "ok", redeploy: "no-op", legacyText: "preserved" }; sql.close();
    const { prisma } = await import("../src/lib/prisma"); disconnect = () => prisma.$disconnect();
    const structure = await import("../src/lib/competition-structure-service");
    const service = await import("../src/lib/referee-service");
    const admissions = await import("../src/lib/referee-admission-service");
    const media = await import("../src/lib/admin-media-service");
    const cms = await import("../src/lib/admin-content-service");
    const content = await import("../src/lib/admin-content-input");
    const imports = await import("../src/lib/competition-import-service");
    const parser = await import("../src/lib/competition-import-parser");
    const auth = await import("./security-r4a-test-capabilities");
    const r1 = await import("../src/lib/referee-r1-service");
    const actor = auth.testUnifiedAdminActor({ roles: ["COMPETITION_ADMIN"] });
    const competitionGrant = auth.issueTestAdminServiceAuthorization("competitions:write", actor);
    const refereeGrant = auth.issueTestAdminServiceAuthorization("referees:write");
    const contentActor = auth.testUnifiedAdminActor({ roles: ["CONTENT_EDITOR"] });
    const fail = async (work: () => Promise<unknown>) => assert.rejects(work);
    for (const url of ["/admin/referees", "/admin/referees/x", "/admin/referees/admissions", "/admin/referees/admissions/x", "/admin/referees/availability", "/admin/competitions/import", "/admin/competitions/x", "/admin/team-directory"]) {
      const hrefs = ["/admin", "/admin/referees", "/admin/referees/admissions", "/admin/referees/availability", "/admin/competitions", "/admin/competitions/import", "/admin/team-directory"].map((href) => ({ href }));
      const expected = hrefs.filter((h) => url === h.href || h.href !== "/admin" && url.startsWith(h.href + "/")).sort((a, b) => b.href.length - a.href.length)[0]?.href;
      assert.equal(activeAdminHref(url, hrefs), expected);
    }
    assert.equal(activeAdminHref("/admin/referees/admissions/x", [{ href: "/admin/referees" }]), "/admin/referees"); assert.equal(activeAdminHref("/admin/referees-other", [{ href: "/admin/referees" }]), undefined); evidence["NAV-01"] = "PASS";
    for (let i = 0; i < 305; i++) await prisma.refereeAdmissionApplication.create({ data: { name: `合成申请${i}`, studentId: `synthetic-${i}`, status: "PENDING" } });
    const refActor = auth.testUnifiedAdminActor({ roles: ["REFEREE_ADMIN"] });
    const queue = await admissions.getAdmissionQueuePage("PENDING", 11, refActor); assert.equal(queue.counts.PENDING, 305); assert.equal(queue.items.length, 5);
    const app = queue.items[0]; const reviewed = await Promise.allSettled([admissions.reviewRefereeAdmissionApplication(app.id, { action: "REJECT", reviewNote: "合成拒绝" }, refActor), admissions.reviewRefereeAdmissionApplication(app.id, { action: "REJECT", reviewNote: "并发拒绝" }, refActor)]); assert.equal(reviewed.filter((r) => r.status === "fulfilled").length, 1); assert.equal((await admissions.getAdmissionQueuePage("PENDING", 1, refActor)).counts.PENDING, 304);
    const college = await prisma.college.create({ data: { name: "隔离审批学院" } });
    await prisma.collegeCodeMapping.create({ data: { prefix: "ZZ", collegeId: college.id } });
    const approval = await prisma.refereeAdmissionApplication.create({ data: { name: "合成并发批准", studentId: "ZZ260001" } });
    const refereesBefore = await prisma.referee.count();
    const approveInput = { action: "APPROVE" as const, mode: "CREATE_NEW" as const, reviewNote: "合成审批" };
    const approved = await Promise.allSettled([admissions.reviewRefereeAdmissionApplication(approval.id, approveInput, refActor), admissions.reviewRefereeAdmissionApplication(approval.id, approveInput, refActor)]);
    assert.equal(approved.filter((r) => r.status === "fulfilled").length, 1);
    assert.equal(await prisma.referee.count(), refereesBefore + 1);
    assert.equal(await prisma.auditLog.count({ where: { entityId: approval.id, action: "REFEREE_ADMISSION_APPROVED" } }), 1);
    const invalid = await prisma.refereeAdmissionApplication.create({ data: { name: "合成无学院映射", studentId: "XY260001" } });
    await fail(() => admissions.reviewRefereeAdmissionApplication(invalid.id, approveInput, refActor));
    assert.equal((await prisma.refereeAdmissionApplication.findUniqueOrThrow({ where: { id: invalid.id } })).status, "PENDING");
    evidence["ADM-01/02"] = { pendingBeyond300: true, concurrentRejectWinners: 1, concurrentApproveAccounts: 1, failedReviewRolledBack: true };
    const competition = await prisma.competition.create({ data: { slug: "ops-36", name: "合成36场测试赛事", campus: "隔离环境", format: "FUTSAL", playingFormat: "五人制", status: "ONGOING", publicPublished: true, homepageFeatured: true } });
    const stage = await structure.mutateCompetitionStructure(competition.id, { action: "stage", name: "小组赛", type: "GROUP", sortOrder: 0 }, actor) as { id: string };
    const teams = await Promise.all(Array.from({ length: 16 }, (_, i) => prisma.team.create({ data: { competitionId: competition.id, name: `合成球队${i + 1}` } })));
    const groups: Array<{ id: string }> = [];
    for (let i = 0; i < 4; i++) {
      const g = await structure.mutateCompetitionStructure(competition.id, { action: "group", stageId: stage.id, name: `${"ABCD"[i]}组`, sortOrder: i }, actor) as { id: string }; groups.push(g);
      await structure.mutateCompetitionStructure(competition.id, { action: "members", groupId: g.id, teamIds: teams.slice(i * 4, i * 4 + 4).map((t) => t.id), reason: "人工抽签记录" }, actor);
      for (let r = 1; r <= 3; r++) await structure.mutateCompetitionStructure(competition.id, { action: "round", stageId: stage.id, groupId: g.id, name: `第${r}轮`, sortOrder: r }, actor);
    }
    await fail(() => structure.mutateCompetitionStructure(competition.id, { action: "members", groupId: groups[1].id, teamIds: [teams[0].id], reason: "错误跨组" }, actor));
    const now = Date.now(); const rows = [];
    for (let g = 0; g < 4; g++) for (let i = 0; i < 9; i++) rows.push({ rowNumber: rows.length + 2, values: { homeTeam: teams[g * 4 + i % 4].name, awayTeam: teams[g * 4 + (i + 1) % 4].name, kickoff: new Date(now + (rows.length + 1) * 86400000).toISOString(), venue: "隔离球场", stage: "小组赛", group: `${"ABCD"[g]}组`, round: `第${i % 3 + 1}轮` } });
    const input = { competitionId: competition.id, importType: "MATCH" as const, inputMethod: "PASTE" as const, inputHash: "synthetic-36", rows, inputWarnings: [] };
    const matchesBefore = await prisma.match.count(), preview = await imports.buildCompetitionImportPreview(input); assert.equal(preview.summary.createRows, 36); assert.equal(await prisma.match.count(), matchesBefore); assert.equal(preview.publicImpact, true);
    const imported = await imports.commitCompetitionImport({ ...input, expectedPlanHash: preview.planHash }, competitionGrant); assert.equal(imported.createdMatches, 36);
    const again = await imports.buildCompetitionImportPreview(input); assert.equal((await imports.commitCompetitionImport({ ...input, expectedPlanHash: again.planHash }, competitionGrant)).createdMatches, 0);
    const bad = { ...input, rows: [{ ...rows[0], values: { ...rows[0].values, homeTeam: teams[5].name } }], inputHash: "bad-group" }; assert.equal((await imports.buildCompetitionImportPreview(bad)).summary.errorRows, 1); await fail(() => imports.commitCompetitionImport(bad, competitionGrant)); assert.equal(await prisma.match.count(), matchesBefore + 36);
    const mapped = parser.parseCompetitionImportCsv("本方,对方,日期,球场,比赛阶段,分组,轮次\n甲,乙,2030-10-15 18:30,球场,小组赛,A组,第1轮", "MATCH", { 本方: "homeTeam", 对方: "awayTeam", 日期: "kickoff", 球场: "venue" }); assert.equal(mapped.rows[0].values.group, "A组");
    await fail(() => structure.mutateCompetitionStructure(competition.id, { action: "delete", entity: "group", id: groups[0].id }, actor));
    await fail(() => structure.mutateCompetitionStructure(competition.id, { action: "members", groupId: groups[0].id, teamIds: [teams[0].id], reason: "不能移出引用成员" }, actor)); evidence["STR-01/02/IMP-01/02/03/04"] = { imported: 36, duplicateCreated: 0, grouped: true, previewWrites: 0 };

    const concurrentPlan = { ...input, inputHash: "preview-concurrent", rows: [{ ...rows[0], values: { ...rows[0].values, kickoff: new Date(Date.now() + 70 * 86400000).toISOString() } }] };
    const stalePreview = await imports.buildCompetitionImportPreview(concurrentPlan);
    await prisma.competition.update({ where: { id: competition.id }, data: { publicPublished: false } });
    await fail(() => imports.commitCompetitionImport({ ...concurrentPlan, expectedPlanHash: stalePreview.planHash }, competitionGrant));
    assert.equal(await prisma.match.count(), matchesBefore + 36);
    await prisma.competition.update({ where: { id: competition.id }, data: { publicPublished: true } });
    const match = await prisma.match.findFirstOrThrow({ where: { competitionId: competition.id, groupId: groups[0].id }, orderBy: { kickoff: "asc" } });

    await fail(() => prisma.match.update({ where: { id: match.id }, data: { groupId: groups[1].id } }));
    assert.equal((await prisma.match.findUniqueOrThrow({ where: { id: match.id } })).groupId, groups[0].id);
    const resultInput = { homeScore: 0, awayScore: 0, homePenaltyScore: null, awayPenaltyScore: null, expectedVersion: 0, actualEnded: true, reason: "合成确认" };
    await fail(() => service.confirmMatchResult(match.id, resultInput, competitionGrant));
    await fail(() => service.updateMatch(match.id, { ...match, endAt: undefined, round: match.round ?? undefined, source: "MANUAL", externalMatchId: undefined, applicationDeadline: undefined, publicNote: undefined, internalNote: undefined, status: "COMPLETED", cancellationReason: undefined, positionCounts: {} }));
    const referee = await prisma.referee.create({ data: { publicCode: "OPS-REF", name: "合成执裁人", assignmentEligibility: "ELIGIBLE", capabilities: { create: { format: "FUTSAL", positionKey: "REFEREE", status: "READY" } } } });
    const draft = await service.saveAppointmentDraft({ matchId: match.id, publicationNote: "合成", positions: [{ key: "REFEREE", slot: 1, refereeId: referee.id }] }, refereeGrant);
    assert.equal(draft.appointment.status, "DRAFT"); await service.publishAppointment(match.id, "", "", refereeGrant);
    await fail(() => service.completeAppointment(match.id, "未来不能完成", refereeGrant));
    const firstAck = await r1.acknowledgeAppointment(draft.appointment.id, referee.id);
    await service.withdrawAppointment(match.id, "合成撤回", refereeGrant); await fail(() => r1.acknowledgeAppointment(draft.appointment.id, referee.id));
    await service.publishAppointment(match.id, "合成重新发布", "", refereeGrant); const secondAck = await r1.acknowledgeAppointment(draft.appointment.id, referee.id); assert.notEqual(firstAck.versionId, secondAck.versionId);
    await fail(() => service.publishAppointment(match.id, "禁止赛事管理员写裁判", "", competitionGrant as never));
    await prisma.match.update({ where: { id: match.id }, data: { kickoff: new Date(now - 7200000), endAt: new Date(now - 3600000) } });
    const result = await service.confirmMatchResult(match.id, resultInput, competitionGrant); assert.equal(result.resultVersion, 1); assert.equal((await prisma.refereeAppointment.findUniqueOrThrow({ where: { matchId: match.id } })).status, "COMPLETED");
    assert.equal((await service.confirmMatchResult(match.id, resultInput, competitionGrant)).resultVersion, 1); assert.equal(await prisma.appointmentVersion.count({ where: { appointmentId: draft.appointment.id, status: "COMPLETED" } }), 1);
    await fail(() => service.confirmMatchResult(match.id, { ...resultInput, homeScore: -1 }, competitionGrant)); await fail(() => service.confirmMatchResult(match.id, { ...resultInput, homeScore: 0.5 }, competitionGrant));
    await fail(() => service.confirmMatchResult(match.id, { ...resultInput, homePenaltyScore: 5, awayPenaltyScore: 4 }, competitionGrant));
    let table = await structure.getGroupStandings(groups[0].id); assert.equal(table.rows.reduce((sum, r) => sum + r.points, 0), 2); assert.equal(table.rows.reduce((sum, r) => sum + r.played, 0), 2);
    await structure.confirmGroup(competition.id, groups[0].id, { kind: "RANKING", teamIds: table.rows.map((r) => r.id), fingerprint: table.fingerprint, reason: "合成竞赛规程" }, actor);
    table = await structure.getGroupStandings(groups[0].id); assert(table.rankingConfirmed);
    await structure.confirmGroup(competition.id, groups[0].id, { kind: "QUALIFICATION", teamIds: [table.rows[0].id], fingerprint: table.qualificationFingerprint, reason: "提前确认：合成例外依据" }, actor);
    const matchesCount = await prisma.match.count(); assert.equal((await structure.getGroupStandings(groups[0].id)).qualifiedTeamIds.length, 1); assert.equal(await prisma.match.count(), matchesCount);
    await fail(() => structure.confirmGroup(competition.id, groups[0].id, { kind: "QUALIFICATION", teamIds: [teams[5].id], fingerprint: table.qualificationFingerprint, reason: "提前确认：错误跨组" }, actor));
    await service.confirmMatchResult(match.id, { ...resultInput, homeScore: 2, expectedVersion: 1, reason: "合成比分更正" }, competitionGrant); table = await structure.getGroupStandings(groups[0].id); assert(table.rankingStale && table.qualificationStale); assert.equal(table.rows[0].points, 3); assert.equal((await r1.getCompletedRefereeStatistics()).find((s) => s.refereeId === referee.id)?.totalMatches, 1);
    await fail(() => service.confirmMatchResult(match.id, { ...resultInput, homeScore: 3, expectedVersion: 1, reason: "过期提交" }, competitionGrant));
    const resultRace = await Promise.allSettled([service.confirmMatchResult(match.id, { ...resultInput, homeScore: 3, expectedVersion: 2, reason: "并发一" }, competitionGrant), service.confirmMatchResult(match.id, { ...resultInput, homeScore: 4, expectedVersion: 2, reason: "并发二" }, competitionGrant)]);
    assert.equal(resultRace.filter((r) => r.status === "fulfilled").length, 1);
    assert.equal(await prisma.appointmentVersion.count({ where: { appointmentId: draft.appointment.id, status: "COMPLETED" } }), 1);
    const knockout = await structure.mutateCompetitionStructure(competition.id, { action: "stage", name: "淘汰赛", type: "KNOCKOUT", sortOrder: 1 }, actor) as { id: string };
    const penaltyMatch = await prisma.match.create({ data: { slug: "ops-penalty", status: "SCHEDULED", competitionId: competition.id, stageId: knockout.id, stage: "淘汰赛", kickoff: new Date(now - 7200000), endAt: new Date(now - 3600000), venue: "隔离", homeTeamId: teams[0].id, awayTeamId: teams[4].id } });
    for (const value of [{ homeScore: null }, { awayScore: null }, { homePenaltyScore: 5, awayPenaltyScore: null }, { homePenaltyScore: 5, awayPenaltyScore: 5 }, { homePenaltyScore: -1, awayPenaltyScore: 2 }, { homePenaltyScore: 1.5, awayPenaltyScore: 2 }]) await fail(() => service.confirmMatchResult(penaltyMatch.id, { ...resultInput, ...value } as unknown as Parameters<typeof service.confirmMatchResult>[1], competitionGrant));
    const penalties = await service.confirmMatchResult(penaltyMatch.id, { ...resultInput, homeScore: 1, awayScore: 1, homePenaltyScore: 5, awayPenaltyScore: 4 }, competitionGrant);
    assert.equal(penalties.homeScore, 1); assert.equal(penalties.awayScore, 1); assert.equal(penalties.homePenaltyScore, 5);
    await prisma.match.update({ where: { id: penaltyMatch.id }, data: { status: "CANCELLED" } });
    await fail(() => service.confirmMatchResult(penaltyMatch.id, { ...resultInput, expectedVersion: 1 }, competitionGrant));
    evidence["RES-extra"] = { optimisticRaceWinners: 1, penaltyScoreSeparate: "1:1 (5:4)", missingNegativeFractionFutureCancelledRejected: true };
    evidence["REF-01/02/03/04/RES-01/02/TAB-01/02/QUAL-01"] = "PASS";
    const pure = calculateStandings([{ id: "a", name: "甲" }, { id: "b", name: "乙" }], [{ homeTeamId: "a", awayTeamId: "b", homeScore: 0, awayScore: 0, status: "COMPLETED", isTestData: false }]); assert.deepEqual(pure.map((r) => [r.played, r.drawn, r.points]), [[1, 1, 1], [1, 1, 1]]);
    const pdf1 = await media.storeMediaAssetUpload({ fileName: "合成原件.pdf", mimeType: "application/pdf", bytes: Buffer.from("%PDF-1.4\nfixture one\n"), visibility: "PUBLIC", actor: contentActor });
    const pdf2 = await media.storeMediaAssetUpload({ fileName: "合成附件.pdf", mimeType: "application/pdf", bytes: Buffer.from("%PDF-1.4\nfixture two\n"), visibility: "PRIVATE", actor: contentActor });
    const postInput = { type: "DISCIPLINE" as const, slug: "ops-content", title: "合成纪律处罚", summary: "合成摘要", content: content.createEmptyStructuredContent("正文先于附件"), status: "DRAFT" as "DRAFT" | "PUBLISHED", discipline: { officialMediaId: pdf1.id }, attachments: [{ mediaAssetId: pdf1.id, displayName: "正式原件" }, { mediaAssetId: pdf2.id, displayName: "补充附件" }] };
    const post = await cms.createContentPost(postInput, contentActor); assert.equal(post.attachments.length, 2);
    await fail(() => cms.updateContentPost(post.id, { ...postInput, status: "PUBLISHED" }, contentActor)); await media.changeMediaVisibility(pdf2.id, "PUBLIC", contentActor);
    const published = await cms.updateContentPost(post.id, { ...postInput, status: "PUBLISHED", attachments: [...postInput.attachments].reverse() }, contentActor); assert.equal(published.attachments[0].mediaAssetId, pdf2.id);
    const projection = await cms.getPublishedContentDetailBySlug(post.slug); assert.equal(projection?.attachments.length, 2); assert(projection?.discipline?.officialMedia); assert(!JSON.stringify(projection).includes("storageKey"));
    const library = await media.getAdminMediaPage({ actor: contentActor, category: "files", query: "合成" }); assert.equal(library.counts.files, 3); assert.equal(library.items.find((a) => a.id === pdf1.id)?.usageCount, 1);
    await fail(() => media.changeMediaVisibility(pdf1.id, "PRIVATE", contentActor));
    await cms.updateContentPost(post.id, { ...postInput, status: "PUBLISHED", attachments: [{ mediaAssetId: pdf1.id }] }, contentActor); assert(await prisma.mediaAsset.findUnique({ where: { id: pdf2.id } })); assert.equal((await media.getAdminMediaPage({ actor: contentActor, query: "合成附件" })).items[0].usageCount, 0);
    await fail(() => cms.updateContentPost(post.id, { ...postInput, slug: "changed-url" }, contentActor));
    for (const type of ["NEWS", "ANNOUNCEMENT", "DISCIPLINE"] as const) for (const status of ["DRAFT", "PUBLISHED", "ARCHIVED"] as const) for (let index = 0; index < 2; index++) {
      await cms.createContentPost({ ...postInput, slug: `ops-grid-${type.toLowerCase()}-${status.toLowerCase()}-${index}`, title: `检索矩阵-${type}-${status}-${index}`, type, status, attachments: [], discipline: type === "DISCIPLINE" ? postInput.discipline : null }, contentActor);
    }
    for (const type of ["NEWS", "ANNOUNCEMENT", "DISCIPLINE"] as const) for (const status of ["DRAFT", "PUBLISHED", "ARCHIVED"] as const) {
      const filtered = await cms.getAdminContentPage({ actor: contentActor, page: 1, type, status, query: "检索矩阵" });
      assert.equal(filtered.total, 2); assert.equal(filtered.items.length, 2); assert.deepEqual(filtered.counts, { NEWS: 2, ANNOUNCEMENT: 2, DISCIPLINE: 2 });
    }
    const gridFirst = await cms.getAdminContentPage({ actor: contentActor, page: 1, query: "检索矩阵" }), gridSecond = await cms.getAdminContentPage({ actor: contentActor, page: 2, query: "检索矩阵" });
    assert.equal(gridFirst.total, 18); assert.equal(new Set([...gridFirst.items, ...gridSecond.items].map((p) => p.id)).size, 18);
    assert.equal((await cms.getAdminContentPage({ actor: contentActor, page: 1, query: "ops-grid-news" })).total, 6);
    const imageAsset = await media.storeMediaAssetUpload({ fileName: "合成正文封面.png", mimeType: "image/png", bytes: Buffer.from([0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a,1]), visibility: "PRIVATE", actor: contentActor });
    const imagePostInput: ContentPostInput = { type: "NEWS", slug: "ops-image-usage", title: "合成图片引用", summary: "图片引用权限", status: "DRAFT", coverMediaId: imageAsset.id, content: { schemaVersion: 1, document: { type: "doc", content: [{ type: "image", attrs: { src: `/media/${imageAsset.id}`, alt: "合成图片" } }] } } };
    const imagePost = await cms.createContentPost(imagePostInput, contentActor);
    await fail(() => cms.updateContentPost(imagePost.id, { ...imagePostInput, status: "PUBLISHED" }, contentActor));
    await media.changeMediaVisibility(imageAsset.id, "PUBLIC", contentActor); await cms.updateContentPost(imagePost.id, { ...imagePostInput, status: "PUBLISHED" }, contentActor);
    const imageLibrary = await media.getAdminMediaPage({ actor: contentActor, category: "images", query: "合成正文封面", visibility: "PUBLIC" });
    assert.equal(imageLibrary.counts.images, 1); assert.equal(imageLibrary.counts.files, 0); assert.equal(imageLibrary.items[0].usageCount, 1);
    await fail(() => media.changeMediaVisibility(imageAsset.id, "PRIVATE", contentActor));
    evidence["CMS-query-matrix"] = { combinations: 9, matchedRowsEach: 2, twoPageUniqueRows: 18, searchBySlug: 6, privateCoverBodyRejected: true, coverBodyUseDeduplicated: 1 };
    const file = await media.resolveMediaAssetFile(pdf1.id, contentActor); await rm(file.filePath); await fail(() => cms.updateContentPost(post.id, { ...postInput, status: "PUBLISHED" }, contentActor));
    evidence["CMS-01/02/03/MED-01"] = "PASS";
    const historic = await prisma.match.create({ data: { slug: "ops-unstructured-history", competitionId: competition.id, stage: "保留旧阶段文字", round: "保留旧轮次文字", kickoff: new Date(Date.now() - 7200000), venue: "隔离", homeTeamId: teams[0].id, awayTeamId: teams[1].id, status: "COMPLETED", homeScore: 0, awayScore: 0 } });
    const classification = { ...historic, cancellationReason: undefined, stageId: stage.id, groupId: groups[0].id, roundId: null, endAt: undefined, round: historic.round ?? undefined, source: "MANUAL" as const, applicationDeadline: undefined, externalMatchId: undefined, publicNote: undefined, internalNote: undefined, positionCounts: {} };
    await fail(() => service.updateMatch(historic.id, classification));
    const classified = await service.updateMatch(historic.id, { ...classification, structureChangeReason: "人工核对历史秩序册及积分影响" });
    assert.equal(classified.stage, historic.stage); assert.equal(classified.round, historic.round); assert.equal(classified.homeScore, 0); assert.equal(classified.awayScore, 0);
    assert.equal(classified.id, historic.id); assert.equal(classified.resultVersion, 0);
    assert.equal((await prisma.auditLog.findFirstOrThrow({ where: { entityId: historic.id, action: "MATCH_UPDATED" } })).metadata?.includes("人工核对历史"), true);
    evidence["STR-historical-classification"] = { explicitReasonRequired: true, oldTextScoresIdsVersionsPreserved: true };
    evidence.finishedAt = new Date().toISOString(); await writeFile("docs/ops-r3-1/evidence/ops-integration.json", JSON.stringify(evidence, null, 2)); console.log(JSON.stringify(evidence, null, 2));
  } finally { await disconnect?.(); await rm(root, { recursive: true, force: true }); }
}
main().catch((e) => { console.error(e); process.exitCode = 1; });
