import { unzipSync, zipSync, strFromU8, strToU8 } from "fflate";
import { PrismaClient } from "../src/generated/prisma-v29/client";
import { PrismaLibSql } from "@prisma/adapter-libsql";
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { mkdtemp, readFile, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
async function main() {
  const root = await mkdtemp(path.join(os.tmpdir(), "nuaafa-ops-r312-"));
  process.env.DATABASE_URL = `file:${path.join(root, "test.db")}`;
  process.env.NUAAFA_UPLOAD_DIR = path.join(root, "uploads");
  process.env.NUAAFA_ISOLATED_SECURITY_TEST = "1";
  await writeFile(path.join(root, "test.db"), "");
  const cli = spawnSync(process.execPath, [path.resolve("node_modules/prisma/build/index.js"), "migrate", "deploy"], { env: process.env, encoding: "utf8" });
  assert.equal(cli.status, 0, cli.stdout + cli.stderr);
  const measuredPrisma = new PrismaClient({ adapter: new PrismaLibSql({ url: process.env.DATABASE_URL! }), log: [{ emit: "event", level: "query" }] });
  let queryCount = 0; measuredPrisma.$on("query", () => queryCount++);
  (globalThis as unknown as { refereePrisma: PrismaClient }).refereePrisma = measuredPrisma;
  const { prisma } = await import("../src/lib/prisma");
  const { testUnifiedAdminActor, issueTestAdminServiceAuthorization } = await import("./security-r4a-test-capabilities");
  const actor = testUnifiedAdminActor({ roles: ["COMPETITION_ADMIN", "REFEREE_ADMIN"] });
  const grant = issueTestAdminServiceAuthorization("competitions:write", actor);
  const refGrant = issueTestAdminServiceAuthorization("referees:write", actor);
  const { mutateCompetitionStructure: mutate, loadCompetitionStructure, getCompetitionGroupStandings } = await import("../src/lib/competition-structure-service");
  const { buildCompetitionImportPreview: preview, commitCompetitionImport: commit } = await import("../src/lib/competition-import-service");
  const { createMatch, updateMatch, createRefereeApplication, createAdminApplicationException, confirmMatchResult, publishAppointment } = await import("../src/lib/referee-service");
  const { scheduleMatch } = await import("../src/lib/match-scheduling-service");
  const { detectAppointmentWarnings } = await import("../src/lib/referee-conflicts");
  const { parseCompetitionImportDocx } = await import("../src/lib/competition-import-docx");
  try {
    const competition = await prisma.competition.create({ data: { slug: "ops-r312", name: "OPS-R3.1.2 16组隔离赛事", format: "FUTSAL", campus: "隔离", status: "ONGOING", publicPublished: true, homepageFeatured: true } });
    await mutate(competition.id, { action: "stage", name: "小组赛", type: "GROUP", sortOrder: 0 }, actor);
    const stage = (await loadCompetitionStructure(competition.id))[0];
    for (let i = 0; i < 12; i++) await mutate(competition.id, { action: "group", stageId: stage.id, name: `${String.fromCharCode(65 + i)}组`, sortOrder: i }, actor);
    let groups = (await loadCompetitionStructure(competition.id))[0].groups;
    assert.deepEqual(groups.map((g) => g.name), Array.from({ length: 12 }, (_, i) => `${String.fromCharCode(65 + i)}组`));
    await assert.rejects(() => mutate(competition.id, { action: "group", stageId: stage.id, name: "A组", sortOrder: 0 }, actor), /同名/);
    console.log("PASS GROUP-01: 12 groups create/order/read, scoped unique names");
    await prisma.team.createMany({ data: Array.from({ length: 72 }, (_, i) => ({ id: `r312-team-${i}`, competitionId: competition.id, name: `球队${String(i + 1).padStart(2, "0")}` })) });
    const teams = await prisma.team.findMany({ where: { competitionId: competition.id }, orderBy: { name: "asc" } });
    for (const [i, g] of groups.entries()) await mutate(competition.id, { action: "assign", stageId: stage.id, groupId: g.id, teamIds: teams.slice(i * 6, i * 6 + 6).map((t) => t.id), reason: "隔离抽签" }, actor);
    groups = (await loadCompetitionStructure(competition.id))[0].groups;
    assert(groups.every((g) => g.members.length === 6)); assert.equal(groups.flatMap((g) => g.members).length, 72);
    await mutate(competition.id, { action: "assign", stageId: stage.id, groupId: null, teamIds: [teams[0].id], reason: "移回未分组" }, actor);
    assert.equal(await prisma.teamGroupMembership.count({ where: { stageId: stage.id } }), 71);
    await mutate(competition.id, { action: "assign", stageId: stage.id, groupId: groups[1].id, teamIds: [teams[0].id], reason: "合法换组" }, actor);
    await assert.rejects(() => prisma.teamGroupMembership.create({ data: { stageId: stage.id, groupId: groups[0].id, teamId: teams[0].id } }));
    await mutate(competition.id, { action: "assign", stageId: stage.id, groupId: groups[0].id, teamIds: [teams[0].id], reason: "换回" }, actor);
    console.log("PASS GROUP-02/03: 72 teams bulk assign/remove/move, one membership per stage");
    const other = await prisma.competitionStage.create({ data: { competitionId: competition.id, name: "第二阶段", type: "GROUP" } });
    const otherGroup = await prisma.competitionGroup.create({ data: { stageId: other.id, name: "A组" } });
    await mutate(competition.id, { action: "assign", stageId: other.id, groupId: otherGroup.id, teamIds: [teams[0].id], reason: "后续阶段" }, actor);
    assert.equal(await prisma.teamGroupMembership.count({ where: { teamId: teams[0].id } }), 2);
    console.log("PASS GROUP-04: independent memberships in different stages");
    const rounds = await Promise.all(groups.map((g) => prisma.competitionRound.create({ data: { stageId: stage.id, groupId: g.id, name: "第1轮" } })));
    const input = (rows: { rowNumber: number; values: Record<string, string> }[]) => ({ competitionId: competition.id, importType: "MATCH" as const, inputMethod: "DOCX" as const, inputHash: "r312", inputWarnings: [], rows });
    const rows = [7, 11].map((index, i) => ({ rowNumber: i + 1, values: { stage: "小组赛", group: groups[index].name, round: "第1轮", matchNumber: String(i + 1), homeTeam: teams[index * 6].name, awayTeam: teams[index * 6 + 1].name, kickoff: "", date: "", time: "", venue: "" } }));
    const p = await preview(input(rows)); assert.equal(p.summary.errorRows, 0); assert.equal(p.summary.warningRows, 2); assert.deepEqual(p.rows.map((r) => r.normalized.group), ["H组", "L组"]);
    assert(p.rows.every((r) => r.warnings.map((w) => w.message).join().includes("比赛时间待安排") && r.warnings.map((w) => w.message).join().includes("比赛场地待安排")));
    const missing = await preview(input([{ ...rows[0], values: { ...rows[0].values, group: "M组" } }])); assert(missing.rows[0].errors.some((e) => e.message.includes("未找到小组“M组”"))); assert.equal(await prisma.competitionGroup.count({ where: { stageId: stage.id, name: "M组" } }), 0);
    const mismatch = await preview(input([{ ...rows[0], values: { ...rows[0].values, homeTeam: teams[0].name, awayTeam: teams[1].name } }]));
    const issue = mismatch.rows[0].errors.find((e) => e.errorCode === "GROUP_TEAM_MISMATCH")!; assert.deepEqual(issue.teamNames, [teams[0].name, teams[1].name]); assert.equal(issue.groupName, "H组");
    console.log("PASS GROUP-05/06/07: H/L dynamic matching, M unmatched without creation, exact mismatch names");
    const result = await commit({ ...input(rows), expectedPlanHash: p.planHash }, grant); assert.equal(result.createdMatches, 2);
    const matches = await prisma.match.findMany({ where: { competitionId: competition.id }, orderBy: { matchNumber: "asc" } }); assert(matches.every((m) => m.kickoff === null && m.venue === null));
    const repeat = await preview(input(rows)); assert.equal(repeat.summary.skipRows, 2);
    const referee = await prisma.referee.create({ data: { publicCode: "R312-REF", name: "隔离裁判" } });
    await assert.rejects(() => createRefereeApplication({ matchId: matches[0].id, refereeId: referee.id, preferredPositions: ["REFEREE"] }), /待排期/);
    await assert.rejects(() => createAdminApplicationException({ matchId: matches[0].id, refereeId: referee.id, preferredPositions: ["REFEREE"], exceptionReason: "隔离" }), /待排期/);
    await prisma.refereeAppointment.create({ data: { matchId: matches[0].id, status: "DRAFT" } });
    await assert.rejects(() => publishAppointment(matches[0].id, "隔离", "", refGrant), /待排期/);
    await assert.rejects(() => confirmMatchResult(matches[0].id, { homeScore: 1, awayScore: 0, homePenaltyScore: null, awayPenaltyScore: null, expectedVersion: 0, actualEnded: true, reason: "隔离" }, grant));
    await assert.rejects(() => prisma.match.update({ where: { id: matches[0].id }, data: { status: "COMPLETED" } }));
    await assert.rejects(() => prisma.match.update({ where: { id: matches[0].id }, data: { applicationWindowStatus: "OPEN" } }));
    assert.deepEqual(await detectAppointmentWarnings(matches[0].id, [{ key: "REFEREE", refereeId: referee.id }]), []);
    const creation = { slug: "pending-manual", competitionId: competition.id, stage: "小组赛", stageId: stage.id, groupId: groups[0].id, roundId: rounds[0].id, homeTeamId: teams[0].id, awayTeamId: teams[1].id, kickoff: null, venue: null, status: "SCHEDULED" as const, applicationWindowStatus: "CLOSED" as const, positionCounts: {} };
    const manual = await createMatch(creation);
    await assert.rejects(() => createMatch({ ...creation, slug: "bad-open", applicationWindowStatus: "OPEN", applicationDeadline: new Date("2030-01-01") }), /待排期/);
    await assert.rejects(() => createMatch({ ...creation, slug: "time-only-open", kickoff: new Date("2030-10-01"), applicationWindowStatus: "OPEN", applicationDeadline: new Date("2030-01-01") }), /待排期/);
    await assert.rejects(() => createMatch({ ...creation, slug: "venue-only-open", venue: "隔离场地", applicationWindowStatus: "OPEN", applicationDeadline: new Date("2030-01-01") }), /待排期/);
    await assert.rejects(() => updateMatch(manual.id, { ...creation, status: "COMPLETED" }));
    await assert.rejects(() => scheduleMatch(manual.id, { kickoff: new Date("2030-10-01T10:00:00Z"), endAt: new Date("2030-10-01T09:00:00Z"), venue: "隔离场地" }, grant));
    const scheduled = await scheduleMatch(manual.id, { kickoff: new Date("2030-10-01T10:00:00Z"), venue: "隔离场地" }, grant);
    assert(scheduled.kickoff); assert.equal(scheduled.venue, "隔离场地"); assert.equal(scheduled.groupId, manual.groupId); assert.equal(scheduled.applicationWindowStatus, "CLOSED");
    await assert.rejects(() => scheduleMatch(manual.id, { kickoff: new Date(), venue: "重复安排" }, grant), /已安排/);
    const published = await prisma.refereeAppointment.create({ data: { matchId: manual.id, status: "PUBLISHED" } });
    await assert.rejects(() => updateMatch(manual.id, { ...creation, kickoff: scheduled.kickoff, venue: null }), /正式裁判任务/);
    await prisma.refereeAppointment.update({ where: { id: published.id }, data: { status: "CANCELLED" } });
    console.log("PASS PENDING: import/idempotency/manual create, service and DB guards, no conflicts, lightweight schedule");
    await assert.rejects(() => mutate(competition.id, { action: "assign", stageId: stage.id, groupId: groups[1].id, teamIds: [teams[0].id], reason: "危险换组" }, actor), /危险换组.*正式比赛/);
    await assert.rejects(() => prisma.teamGroupMembership.update({ where: { stageId_teamId: { stageId: stage.id, teamId: teams[0].id } }, data: { groupId: groups[1].id } }));
    console.log("PASS GROUP-09: official fixtures block dangerous membership changes");
    queryCount = 0; await getCompetitionGroupStandings(competition.id); const twelveGroupQueryCount = queryCount;
    for (let i = 12; i < 16; i++) await mutate(competition.id, { action: "group", stageId: stage.id, name: `${String.fromCharCode(65 + i)}组`, sortOrder: i }, actor);
    await mutate(competition.id, { action: "group", stageId: stage.id, name: "女子甲组", sortOrder: 20 }, actor);
    const last = (await loadCompetitionStructure(competition.id))[0].groups.at(-1)!;
    await mutate(competition.id, { action: "updateGroup", groupId: last.id, name: "第一小组", sortOrder: 16 }, actor);
    const structure = await loadCompetitionStructure(competition.id); assert.equal(structure[0].groups.length, 17); assert.equal(structure[0].groups.at(-1)?.name, "第一小组");
    const tables = await getCompetitionGroupStandings(competition.id); assert.equal(tables.length, 18); assert.equal(tables.find((t) => t.group.id === groups[0].id)?.rows.length, 6);
    queryCount = 0; await getCompetitionGroupStandings(competition.id); const seventeenGroupQueryCount = queryCount;
    assert(seventeenGroupQueryCount <= twelveGroupQueryCount + 1, `${twelveGroupQueryCount} -> ${seventeenGroupQueryCount} queries`);
    console.log(`PASS GROUP-10: measured SQL queries ${twelveGroupQueryCount} for 12 groups, ${seventeenGroupQueryCount} for 17 groups`);
    const fixtureDocx = await readFile("scripts/fixtures/ops-r3-1-1/2026-09-29_06.43.05-65a5f60ea71e6a7385071a16fed8e472.docx");
    const archive = unzipSync(fixtureDocx); const xml = strFromU8(archive["word/document.xml"]);
    archive["word/document.xml"] = strToU8(xml.replaceAll("A组", "H组").replaceAll("B组", "L组"));
    assert.deepEqual(new Set(parseCompetitionImportDocx(Buffer.from(zipSync(archive))).rows.map((r) => r.values.group)), new Set(["H组", "L组"]));
    archive["word/document.xml"] = strToU8(xml.replaceAll("A组", "女子A组").replaceAll("B组", "第一小组"));
    assert.deepEqual(new Set(parseCompetitionImportDocx(Buffer.from(zipSync(archive))).rows.map((r) => r.values.group)), new Set(["女子A组", "第一小组"]));
    console.log("PASS DOCX parser: H/L and custom group names from actual OOXML");
    assert.equal(parseCompetitionImportDocx(await readFile("scripts/fixtures/ops-r3-1-1/2026-09-29_06.43.05-65a5f60ea71e6a7385071a16fed8e472.docx")).rows.length, 30);
    for (const [i, group] of groups.entries()) {
      if (await prisma.match.count({ where: { groupId: group.id } })) continue;
      await createMatch({ ...creation, slug: `many-groups-${i}`, groupId: group.id, roundId: rounds[i].id, homeTeamId: teams[i * 6].id, awayTeamId: teams[i * 6 + 1].id });
    }
    // Retain isolated data for optional HTTP/browser QA, never write real development DB.
    await writeFile(path.join(root, "fixture.json"), JSON.stringify({ root, databaseUrl: process.env.DATABASE_URL, competitionId: competition.id, stageId: stage.id, pendingMatchId: matches[0].id, scheduledMatchId: manual.id, groupCount: 17, teamCount: 72 }, null, 2));
    console.log(`ISOLATED_FIXTURE=${root}`);
  } finally { await prisma.$disconnect(); }
}
main().catch((error) => { console.error(error); process.exitCode = 1; });
