import assert from "node:assert/strict";
import { mkdtemp, writeFile, readFile } from "node:fs/promises";
import { spawnSync } from "node:child_process";
import path from "node:path";
import os from "node:os";
async function main() {
  const root = await mkdtemp(path.join(os.tmpdir(),"nuaafa-ops-r313-"));
  process.env.DATABASE_URL = `file:${path.join(root,"test.db")}`; process.env.NUAAFA_UPLOAD_DIR=path.join(root,"uploads"); process.env.NUAAFA_ISOLATED_SECURITY_TEST="1";
  await writeFile(path.join(root,"test.db"),"");
  const cli=spawnSync(process.execPath,[path.resolve("node_modules/prisma/build/index.js"),"migrate","deploy"],{env:process.env,encoding:"utf8"});assert.equal(cli.status,0,cli.stdout+cli.stderr);
  const { prisma }=await import("../src/lib/prisma"); const { issueTestAdminServiceAuthorization, testUnifiedAdminActor }=await import("./security-r4a-test-capabilities");
  const grant=issueTestAdminServiceAuthorization("competitions:write");
  const { buildCompetitionImportPreview:preview, commitCompetitionImport:commit }=await import("../src/lib/competition-import-service");
  const { inspectTeamRemoval:inspect, removeCompetitionTeams:remove }=await import("../src/lib/competition-team-removal");
  const { importNameCandidates }=await import("../src/lib/competition-import-matching");
  try {
    const competition=await prisma.competition.create({data:{slug:"r313",name:"R313隔离验收赛事",campus:"隔离",format:"FUTSAL",status:"ONGOING",publicPublished:true}});
    const stage=await prisma.competitionStage.create({data:{competitionId:competition.id,name:"小组赛",type:"GROUP"}});
    const group=await prisma.competitionGroup.create({data:{stageId:stage.id,name:"A组"}});
    const round=await prisma.competitionRound.create({data:{stageId:stage.id,groupId:group.id,name:"第1轮"}});
    const names=["SQA项目队","SQA项目","机电学院","致慧书院一队","致慧书院二队","误加已分组","误加未分组","误加公开队"];
    const teams=await Promise.all(names.map((name)=>prisma.team.create({data:{competitionId:competition.id,name,directoryIsPublic:name==="误加公开队"}})));
    for(const t of teams.filter((t)=>t.name!=="误加未分组")) await prisma.teamGroupMembership.create({data:{teamId:t.id,stageId:stage.id,groupId:group.id}});
    const other=await prisma.competition.create({data:{slug:"r313-other",name:"其他赛事",campus:"隔离",format:"FUTSAL",status:"ONGOING"}});
    const foreign=await prisma.team.create({data:{competitionId:other.id,name:teams[0].name}});
    await prisma.auditLog.create({data:{actorType:"SYSTEM",action:"TEAM_CREATED",entityType:"Team",entityId:teams[5].id,summary:"普通创建历史"}});
    const college=await prisma.college.create({data:{name:"安全移除组织事实"}});
    const unit=await prisma.affiliationUnit.create({data:{name:"安全移除学院事实",type:"COLLEGE"}});
    await prisma.teamAffiliation.create({data:{teamId:teams[5].id,collegeId:college.id}});await prisma.teamUnitAffiliation.create({data:{teamId:teams[5].id,unitId:unit.id}});
    const before=await prisma.team.count();
    await remove(competition.id,[teams[5].id],"误添加",grant);
    assert.equal(await prisma.team.findUnique({where:{id:teams[5].id}}),null);assert.equal(await prisma.teamGroupMembership.count({where:{teamId:teams[5].id}}),0);
    assert(await prisma.college.findUnique({where:{id:college.id}}));assert(await prisma.affiliationUnit.findUnique({where:{id:unit.id}}));
    assert(await prisma.competitionGroup.findUnique({where:{id:group.id}}));assert.equal(await prisma.team.count(),before-1);assert(await prisma.team.findUnique({where:{id:foreign.id}}));
    assert.equal(await prisma.auditLog.count({where:{entityId:teams[5].id,action:"TEAM_CREATED"}}),1);
    await remove(competition.id,[teams[6].id,teams[7].id],"误添加",grant);
    await assert.rejects(()=>remove(competition.id,[foreign.id],"误添加",grant),/当前赛事/);
    await assert.rejects(()=>remove(competition.id,[teams[1].id],"误添加",{} as typeof grant),/授权/);
    console.log("PASS TEAM-REMOVE-01/02: memberships removed, groups/history/other competition preserved, public entry only removed, authorization enforced");
    const input=(rows: {rowNumber:number;values:Record<string,string>}[], extra={})=>({competitionId:competition.id,importType:"MATCH" as const,inputMethod:"DOCX" as const,inputHash:"r313",inputWarnings:[],strictIdentity:true,rows,...extra});
    const row=(n:number,extra={})=>({rowNumber:n,values:{homeTeam:"SQA 项目队",awayTeam:"机电",stage:"小组赛",group:"A组",round:"第1轮",matchNumber:String(n),kickoff:"",date:"",time:"",venue:"",...extra}});
    const rows=Array.from({length:30},(_,i)=>row(i+1));
    const unconfirmed=await preview(input(rows));assert.equal(unconfirmed.summary.errorRows,30);assert.equal(unconfirmed.teamMappings?.find((m)=>m.sourceName==="SQA 项目队")?.affectedRows,30);
    assert.equal(unconfirmed.teamMappings?.find((m)=>m.sourceName==="机电")?.candidates[0].name,"机电学院");
    assert.equal(importNameCandidates("致慧书院",teams).filter((t)=>t.name.startsWith("致慧书院")).length,2);
    assert.equal(importNameCandidates("SQA 项目队",teams)[0].id,teams[0].id);
    await assert.rejects(()=>commit(input(rows),grant),/错误/);
    const mapping={teamMappings:{"SQA 项目队":teams[0].id,"机电":teams[2].id}};
    const confirmed=await preview(input(rows,mapping));assert.equal(confirmed.summary.errorRows,0);assert.equal(confirmed.summary.warningRows,30);
    assert.equal(await prisma.team.count({where:{competitionId:competition.id,name:{in:["SQA项目","SQA项目队"]}}}),2);
    const cross=await preview(input([row(1)],{teamMappings:{"SQA 项目队":foreign.id,"机电":teams[2].id}}));assert(cross.rows[0].errors.some((e)=>e.errorCode==="TEAM_MAPPING_EXPIRED"));
    const same=await preview(input([row(1)],{teamMappings:{"SQA 项目队":teams[0].id,"机电":teams[0].id}}));assert(same.rows[0].errors.some((e)=>e.errorCode==="SAME_TEAM"));
    console.log("PASS IMPORT-MATCH-01..04: deterministic recommendations, one confirmation per source, ambiguity and identity distinctions, no merge, cross competition/same team refused");
    const padded=await preview(input([row(40,{date:"2026-1-2"})],mapping));assert.equal(padded.rows[0].normalized.tentativeDate,"2026-01-02");
    const clock=await preview(input([row(41,{kickoff:"15:30"})],mapping));assert.equal(clock.summary.errorRows,0);assert.equal(clock.rows[0].normalized.kickoff,null);assert.equal(clock.rows[0].normalized.tentativeSchedule,"15:30");
    const partialRows=rows.map((r,i)=> i===0?row(1,{date:"2026-10-09"}):i===1?row(2,{venue:"西操场"}):i===2?row(3,{time:"下午"}):r);
    const subset=input(partialRows,{...mapping,excludedRowNumbers:[29,30]});const p=await preview(subset);assert.equal(p.rows.length,28);assert.equal(p.excludedRows?.length,2);assert.equal(p.summary.errorRows,0);
    const r=await commit({...subset,expectedPlanHash:p.planHash},grant);assert.equal(r.createdMatches,28);assert.equal(await prisma.match.count({where:{competitionId:competition.id,kickoff:null}}),28);
    const first=await prisma.match.findFirstOrThrow({where:{competitionId:competition.id,matchNumber:1}});assert.equal(first.tentativeDate,"2026-10-09");
    assert.equal((await prisma.match.findFirstOrThrow({where:{competitionId:competition.id,matchNumber:2}})).venue,"西操场");
    assert.equal((await prisma.match.findFirstOrThrow({where:{competitionId:competition.id,matchNumber:3}})).tentativeSchedule,"下午");
    const retry=await preview(subset);assert.equal(retry.summary.skipRows,28);
    const bad=await preview(input([row(31,{kickoff:"10/11下午"})],mapping));assert.equal(bad.summary.errorRows,1);
    const pending=input([row(31,{kickoff:"10/11下午",pendingResolution:"pending"})],mapping);const pp=await preview(pending);assert.equal(pp.summary.errorRows,0);await commit({...pending,expectedPlanHash:pp.planHash},grant);
    assert.equal((await prisma.match.findFirstOrThrow({where:{competitionId:competition.id,matchNumber:31}})).tentativeSchedule,"10/11下午");
    const errorInput=input(Array.from({length:28},(_,i)=>row(32+i,i===27?{awayTeam:"未知"}:{})),mapping);await assert.rejects(()=>commit(errorInput,grant),/错误/);assert.equal(await prisma.match.count({where:{competitionId:competition.id,matchNumber:{gte:32,lte:59}}}),0);
    console.log("PASS IMPORT-TIME-01..04/SUBSET-01..02: 28/30 atomic subset, zero fake kickoff, date/venue/text persist, ambiguity explicit pending, duplicate import no overwrite");
    const safeBatch=await Promise.all([1,2,3].map((n)=>prisma.team.create({data:{competitionId:competition.id,name:`安全批量${n}`}})));
    const selection=[...safeBatch.map((t)=>t.id),teams[0].id];const check=await inspect(competition.id,selection);assert.equal(check.teams.filter((t)=>t.removable).length,3);
    await assert.rejects(()=>remove(competition.id,selection,"误添加",grant),/引用/);assert.equal(await prisma.team.count({where:{id:{in:safeBatch.map((t)=>t.id)}}}),3);
    await remove(competition.id,check.teams.filter((t)=>t.removable).map((t)=>t.id),"误添加",grant);assert.equal(await prisma.team.count({where:{id:{in:safeBatch.map((t)=>t.id)}}}),0);
    const groupOnly=await prisma.team.create({data:{competitionId:competition.id,name:"仅移出小组"}});await prisma.teamGroupMembership.create({data:{teamId:groupOnly.id,stageId:stage.id,groupId:group.id}});
    const {mutateCompetitionStructure}=await import("../src/lib/competition-structure-service");await mutateCompetitionStructure(competition.id,{action:"assign",stageId:stage.id,groupId:null,teamIds:[groupOnly.id],reason:"移出本小组"},testUnifiedAdminActor());assert(await prisma.team.findUnique({where:{id:groupOnly.id}}));assert.equal(await prisma.teamGroupMembership.count({where:{teamId:groupOnly.id}}),0);const audit=await prisma.auditLog.findFirstOrThrow({where:{action:"TEAM_GROUP_REMOVED"}});assert(JSON.parse(audit.metadata!).teams.some((t:{teamName:string})=>t.teamName==="仅移出小组"));
    console.log("PASS TEAM-REMOVE-06/group removal: exact 4 selected / 3 safe / 1 blocked, atomic denial then explicit safe-only removal; group removal keeps Team and detailed audit");
    const block=await inspect(competition.id,[teams[0].id,teams[1].id]);assert.equal(block.teams[0].removable,false);assert.equal(block.teams[1].removable,true);
    await assert.rejects(()=>remove(competition.id,[teams[0].id,teams[1].id],"误添加",grant),/引用/);assert(await prisma.team.findUnique({where:{id:teams[1].id}}));
    const cleanPreview=await preview(input([row(35,{homeTeam:"SQA项目"})],{teamMappings:{"机电":teams[2].id}}));assert.equal(cleanPreview.summary.errorRows,0);
    await remove(competition.id,[teams[1].id],"误添加",grant);
    await assert.rejects(()=>commit({...input([row(35,{homeTeam:"SQA项目"})],{teamMappings:{"SQA项目":teams[1].id,"机电":teams[2].id}}),expectedPlanHash:cleanPreview.planHash},grant),/变化|错误/);assert.equal(await prisma.team.count({where:{competitionId:competition.id,name:"SQA项目"}}),0);
    const fresh=await prisma.team.create({data:{competitionId:competition.id,name:"并发预检球队"}});assert((await inspect(competition.id,[fresh.id])).teams[0].removable);
    await prisma.match.create({data:{slug:"race-dependent",competitionId:competition.id,stage:"其他",homeTeamId:fresh.id,awayTeamId:teams[2].id,status:"SCHEDULED"}});
    await assert.rejects(()=>remove(competition.id,[fresh.id],"误添加",grant),/引用/);assert(await prisma.team.findUnique({where:{id:fresh.id}}));
    for(const status of ["SCHEDULED","CANCELLED","COMPLETED"] as const) { await prisma.match.update({where:{id:first.id},data:{status,kickoff:new Date("2026-10-09T07:30:00Z"),venue:"西操场",...(status==="COMPLETED"?{homeScore:1,awayScore:0}:{})}});await assert.rejects(()=>remove(competition.id,[teams[0].id],"误添加",grant),/引用/); }
    for (const kind of ["RANKING", "QUALIFICATION"] as const) { await prisma.groupConfirmation.create({data:{groupId:group.id,kind,teamIds:[teams[3].id],fingerprint:"history",reason:"确认历史"}}); await assert.rejects(()=>remove(competition.id,[teams[3].id],"误添加",grant),/排名|出线/); }
    await assert.rejects(()=>prisma.team.delete({where:{id:teams[3].id}}));
    console.log("PASS TEAM-REMOVE-03..07/IMPORT-DELETE-01: all match statuses protected, explicit safe subset, stale mapping refuses resurrection, dependency added after inspect refuses deletion, confirmation history preserved");
    const scale=await prisma.competition.create({data:{slug:"r313-scale-110",name:"110队导入候选隔离验证",campus:"隔离",format:"FUTSAL",status:"ONGOING",isTestData:true}});
    await prisma.team.createMany({data:Array.from({length:110},(_,i)=>({competitionId:scale.id,name:`验收${String(i+1).padStart(3,"0")}`}))});const scaleTeams=await prisma.team.findMany({where:{competitionId:scale.id},orderBy:{name:"asc"}});
    const scaleInput={competitionId:scale.id,importType:"MATCH" as const,inputMethod:"CSV" as const,inputHash:"scale110",strictIdentity:true,inputWarnings:[],teamMappings:{"验收 001":scaleTeams[0].id},rows:scaleTeams.slice(1).map((t,i)=>({rowNumber:i+1,values:{homeTeam:"验收 001",awayTeam:t.name,stage:"自由赛",matchNumber:String(i+1),kickoff:"",venue:""}}))};const largePreview=await preview(scaleInput);assert.equal(largePreview.summary.errorRows,0);assert.equal(largePreview.rows.length,109);assert.equal(largePreview.teamOptions?.length,110);assert.equal(largePreview.teamMappings?.find((m)=>m.sourceName==="验收 001")?.affectedRows,109);
    console.log("PASS 110-team candidate preview / 109 pending rows / one mapping shared across all rows");
    // Fixture for visual QA, isolated accounts only.
    const { hashPassword }=await import("../src/lib/referee-security");
    await prisma.adminAccount.create({data:{username:"r313-super",displayName:"R313隔离验收",passwordHash:await hashPassword("R313-Isolated-only-verify!"),role:"SUPER_ADMIN"}});
    await prisma.team.createMany({data:[{competitionId:competition.id,name:"误加待移除"},{competitionId:competition.id,name:"误加待批量1"},{competitionId:competition.id,name:"误加待批量2"}]});
    const docx=await readFile("scripts/fixtures/ops-r3-1-1/2026-09-29_06.43.05-65a5f60ea71e6a7385071a16fed8e472.docx");
    const {parseCompetitionImportDocx}=await import("../src/lib/competition-import-docx");const parsed=parseCompetitionImportDocx(docx);
    const demo=await prisma.competition.create({data:{slug:"r313-docx",name:"R313 DOCX人工对应验收",campus:"隔离",format:"FUTSAL",status:"ONGOING"}});const ds=await prisma.competitionStage.create({data:{competitionId:demo.id,name:"小组赛",type:"GROUP"}});
    for(const gn of ["A组","B组"]) {const g=await prisma.competitionGroup.create({data:{stageId:ds.id,name:gn}});for(let i=1;i<=5;i++) await prisma.competitionRound.create({data:{stageId:ds.id,groupId:g.id,name:`第${i}轮`}});for(const name of new Set(parsed.rows.filter((r)=>r.values.group===gn).flatMap((r)=>[String(r.values.homeTeam),String(r.values.awayTeam)]))) {const t=await prisma.team.create({data:{competitionId:demo.id,name:name==="SQA项目"?"SQA项目队":name}});await prisma.teamGroupMembership.create({data:{teamId:t.id,stageId:ds.id,groupId:g.id}});} }
    await writeFile(path.join(root,"fixture.json"),JSON.stringify({root,databaseUrl:process.env.DATABASE_URL,competitionId:competition.id,docxCompetitionId:demo.id,stageId:stage.id,groupId:group.id,roundId:round.id},null,2));console.log(`ISOLATED_FIXTURE=${root}`);
  } finally {await prisma.$disconnect();}
}
main().catch((error)=>{console.error(error);process.exitCode=1;});
